[window]
opacity = 1
#opacity = 0.97

[font]
#normal = { family = "terminal-font", style = "Regular"}
size = 10.0
builtin_box_drawing = true

[cursor]
style = {shape = "Block", blinking = "On"}
blink_interval = 500
blink_timeout = 0

[colors.primary]
foreground = "#202020"
dim_foreground = "#ff0000"
bright_foreground = "#0000ff"
background = "#ffffd7"

[colors.selection]
text = "#ffffd7"
background = "#202020"

[colors.normal]
black = "#1f2024"
red = "#d03636"
green = "#36b93b"
yellow = "#eecc44"
blue = "#0067ff"
magenta = "#e22bb7"
cyan = "#0099cc"
white = "#b7c8d9"

[colors.bright]
black = "#555555"
red = "#d03636"
green = "#36b93b"
yellow = "#eecc44"
blue = "#0067ff"
magenta = "#e22bb7"
cyan = "#0099cc"
white = "#b7c8d9"

[colors.dim]
black = "#1f2024"
red = "#d03636"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0067ff"
magenta = "#b963dc"
cyan = "#0099cc"
white = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#404040"
