[window]
opacity = 1

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "Always" }

[colors.cursor]
cursor = "#dddddd"

[colors.primary]
foreground = "#dddddd"
bright_foreground = "#0000ff"
background = "#222222"

[colors.selection]
text = "#222222"
background = "CellForeground"

[colors.normal]
black = "#222222"
red = "#f25151"
green = "#51f26c"
yellow = "#f2ca51"
blue = "#5194f2"
magenta = "#f251e5"
cyan = "#51f2d7"
white = "#dddddd"
